version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: holberton
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynet

networks:
  mynet:

volumes:
  db_data:
